branding: Merano - Alto Adige/Suedtirol
title: Merano - Alto Adige/Suedtirol
brandNavbar: Merano
brandNavbarLogo: null
brandByDomain:
  localhost:
    branding: Journey 
    title: Journey
    brandNavbar: Journey
    brandNavbarLogo: openmove
  
  mobility.meran.eu:
    branding: Merano - Alto Adige/Suedtirol
    title: Merano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: merano
  mobility.merano.eu:
    branding: Merano - Alto Adige/Suedtirol
    title: Merano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: merano
  mobility.bz.it:
    branding: Bolzano - Alto Adige/Suedtirol
    title: Bolzano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: bolzano
  journey.opendatahub.bz.it:
    branding: Mentor
    title: Mentor
    brandNavbar: ''
    brandNavbarLogo: interreg
configByDomain:
  mobility.bz.it:
    map:
      initLat: 46.492111111111
      initLon: 11.333333333333
      initZoom: 14
reportIssue:
  mailto: support@openmove.com
analytics:
  google:
    globalSiteTag: UA-XXXXX-Y
api:
  host: http://localhost
  path: /otp/routers/openmove
  port: 8080
geocoder:
  baseUrl: http://localhost:8088/v1
  maxNearbyStops: 6
  maxResults: 20
  type: PELIAS
  boundary:
    rect:
      minLon: 10.470121
      maxLon: 12.255011
      minLat: 46.188280
      maxLat: 47.088780
language:
  storageDisclaimer: storage_disclaimer
  routeViewer: route_viewer
  routeViewerDetails: route_view_details
  defaultLanguage: it
  fallbackLanguage: en
routingTypes:
  - key: ITINERARY
    text: exact_time
elevationProfile: true
transitOperators:
  - id: "12"
    logo: http://www.trasporti.provincia.tn.it/binary/pat_trasporti/orari/LogoTT2018.1547032531.jpg
  - id: "1"
    logo: https://www.suedtirolmobil.info/typo3conf/ext/sta_layout/Resources/Public/Images/logo.svg
  - id: "Easymobil"
    logo: https://www.easymobil.it/wp-content/themes/easy_mobil/images/logo.png
persistence:
  enabled: true
  strategy: localStorage
map:
  views:
    - type: DEFAULT
      text: Mappa
  initLat: 46.670953
  initLon: 11.155007
  initZoom: 15
  maxZoom: 20
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
      hasRetinaSupport: true
    - name: Printer
      url: //stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Printer</a>'
    - name: Openstreetmap
      url: //{s}.tile.osm.org/{z}/{x}/{y}.png
      attribution: 'Map data &copy; <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
      maxZoom: 16
  overlays:
    - type: stops
      name: stops
      visible: true
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconColor: "#fff"
      minZoom: 15
      parentStations: true
      minZoomStation: 17
    - type: bike-rental
      name: bikesharing
      modes:
        - BICYCLE_RENT
      companies:
        - BZ
        - ME
        - PAPIN
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#ead896"
      iconColor: "#5d5d5d"
    - type: car-rental
      name: carsharing
      modes:
        - CAR_RENT
      companies:
        - SUEDTIROL
      api: http://localhost:8091/carsharing/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#d9bd48"
      iconColor: "#5d5d5d"
      filters:
        vehiclesModels:
          enabled: true
          label: carsharing_vehicles_models
          values:
            - enabled: true
              value: vw-golf
              label: VW Golf
            - enabled: true
              value: vw-up
              label: VW up!
            - enabled: true
              value: vw-golf-variant
              label: VW Golf Variant
            - enabled: true
              value: vw-caddy
              label: VW Caddy
            - enabled: true
              value: vw-caddy-life
              label: VW Caddy Life
            - enabled: true
              value: vw-id3
              label: VW ID.3
            - enabled: true
              value: vw-egolf
              label: VW e-Golf
            - enabled: true
              value: vw-eup
              label: VW e-UP!
            - enabled: true
              value: renault-zoe
              label: Renault Zoe
            - enabled: true
              value: nissan-leaf-elektro
              label: Nissan Leaf (elektro)
    - type: charger
      name: charger
      api: http://localhost:8093/charger/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#FAA61F"
      iconColor: "#5d5d5d"
      filters:
        provider:
          enabled: true
          label: charger_provider
          values:
            - value: DriWe
              enabled: true
            - value: H2 Center
              enabled: true
            - value: Neogy
              enabled: true
            - value: Route220
              enabled: true
            - value: Alperia Smart Mobility
              enabled: true
        plugsTypes:
          enabled: true
          label: charger_plugstypes
          values:
            - value: 700 bar small vehicles
              enabled: true
            - value: IEC 62196-2 type 2 outlets (all amperage and phase)
              enabled: true
            - value: Type2Mennekes
              enabled: true
            - value: CHAdeMO
              enabled: true
            - value: CCS
              enabled: true
            - value: Schuko
              enabled: true
            - value: OTHER
              enabled: true
        accessType:
          enabled: true
          label: charger_accesstype
          values:
            - value: PUBLIC
              enabled: true
            - value: PRIVATE
              enabled: true
            - value: PRIVATE_WITHPUBLICACCESS
              enabled: true
    - type: parking
      name: parking
      api: http://localhost:8092/parking/all.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#b0d1ef"
      iconColor: "#5d5d5d"
    - type: drt
      name: ondemand
      api: http://localhost:8095/drt/all.json
      pollingInterval: 5000
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconVehicleColor: "#095980"
      iconColor: "#fff"
      pathColor: "#3388ff"
      pathDash: 1,1
      areas:
        1:
          name: 'Area Esterna'
          color: 'red'
        2:
          name: 'Area Principale'
          color: 'green'
        3:
          name: 'Area Esterna'
          color: 'red'
modes:
  transitModes:
    - mode: BUS
      label: bus
    - mode: RAIL
      label: train
    - mode: GONDOLA
      label: funicular
  accessModes:
    - mode: BICYCLE
      label: bike_ride
    - mode: BICYCLE_RENT
      label: bikesharing_ride
    - mode: CAR_PARK
      label: park_ride
    - mode: CAR_RENT
      label: carsharing_ride
    - mode: MICROMOBILITY
      label: micromobility_ride
  exclusiveModes:
    - WALK
    - BICYCLE
    - MICROMOBILITY
  bicycleModes:
    - mode: BICYCLE
      label: my_bike
      iconWidth: 18
    - mode: BICYCLE_RENT
      label: bikesharing
      iconWidth: 36
companies:
    - id: BZ
      label: Bikesharing BZ
      modes: BICYCLE_RENT
    - id: ME
      label: Bikesharing Meran
      modes: BICYCLE_RENT
    - id: PAPIN
      label: Bike Rental Papin
      modes: BICYCLE_RENT
    - id: CAR2GO
      label: CarSharing
      modes: CAR_RENT
errorMessages:
  - id: 404
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.
  - id: 405
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.
  - id: 480
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.
dateTime:
  timeFormat: HH:mm
  dateFormat: DD/MM/YYYY
  longDateFormat: D MMMM YYYY
