server:
  port: 8090
  polling_interval: 10

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #path: /v2
    #headers:
    # User-Agent: OpenMove-Bikesharing-Client
  stations:
    path: /v2/flat%2Cnode/ParkingStation?distinct=true
  sensors:
    path: /v2/flat%2Cnode/ParkingSensor?distinct=true
