branding: Merano - Alto Adige/Suedtirol
title: Merano - Alto Adige/Suedtirol
brandNavbar: Merano
brandNavbarLogo: null

#overwrite default values by location.hostname
brandByDomain:
  localhost:
    branding: Journey 
    title: Journey 
    brandNavbar: Journey
    brandNavbarLogo: openmove
  
  mobility.meran.eu:
    branding: Merano - Alto Adige/Suedtirol
    title: Merano - Alto Adige/Suedtirol
    brandNavbar: ''
    brandNavbarLogo: merano

  mentor.opendatahub.bz.it:
    branding: Mentor
    title: Mentor
    brandNavbar: ''
    brandNavbarLogo: interreg

reportIssue:
  mailto: support@openmove.com

# Default OTP API
api:
  host: ${API_HOST}
  path: ${API_PATH}
  port: ${API_PORT}

geocoder:
  baseUrl: ${GEOCODER_BASEURL}
  maxNearbyStops: 6
  maxResults: 20
  type: PELIAS
  boundary:
    rect:
      minLon: 10.470121
      maxLon: 12.255011
      minLat: 46.188280
      maxLat: 47.088780
      #Suedtirol 10.470121,46.188280,12.255011,47.088780

language:
  storageDisclaimer: storage_disclaimer
  routeViewer: route_viewer
  routeViewerDetails: route_view_details
  defaultLanguage: it
  fallbackLanguage: en
  #SET HERE DEFAULT FRONT-END LANGUAGE

# react-router config, for URL routing (not to be confused with multimodal/OTP routing)
#reactRouter:
#   # If app is to be deployed to a URL subdirectory (e.g. http://foo.bar/app), specify the path here:
#  basename: ${FOLDER}
#
# analytics:
#   google:
#     globalSiteTag: UA-133677388-1

# Enabled multimodal routing types (e.g. interary, profile)
routingTypes:
  - key: ITINERARY
    text: exact_time

  # Delete/uncomment the following block to disable profile routing
  #- key: PROFILE
  #  text: Time Window
  #  api: # Specifies a different API endpoint for profile routing
  #    host: https://otp.openmove.com/router/car
  #    path: /api

# Show/hide elevation profile chart for walk/bike legs
elevationProfile: true

# Provide a list of operators to enhance the user experience for multi-agency
# implementations. The order of the agencies will dictate the order that routes
# appear in the route viewer. Also, optionally provide operator logos to appear
# in narrative itinerary (matched on agency_id). Note: these logos will
# override the values found in agency.txt#agency_branding_url.
transitOperators:
  - id: "12"
    logo: http://www.trasporti.provincia.tn.it/binary/pat_trasporti/orari/LogoTT2018.1547032531.jpg
  - id: "1"
    logo: https://www.suedtirolmobil.info/typo3conf/ext/sta_layout/Resources/Public/Images/logo.svg
  - id: "Easymobil"
    logo: https://www.easymobil.it/wp-content/themes/easy_mobil/images/logo.png

# Add suggested locations to be shown as options in the form view.
# locations:
#   - id: 'airport'
#     icon: 'plane'
#     name: 'Portland International Airport (PDX)'
#     lat: 45.587579
#     lon: -122.593084
#   - id: 'zoo'
#     icon: building
#     lat: 45.51010444232195
#     lon: -122.71607145667079
#     name: Oregon Zoo, Portland, OR

persistence:
  enabled: true
  strategy: localStorage

# Map config
map:
  # Enabled map views
  views:
    - type: DEFAULT
      text: Mappa
    # Delete/uncomment the following block to disable the stylized map
    #- type: STYLIZED
    #  text: Network View

  # Default map center
  initLat: 46.670953
  initLon: 11.155007
  initZoom: 15
  # closer-in zoom levels don't have any tiles that could be rendered by
  maxZoom: 20

  # Base layers for default map
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: 'abcd'
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
      hasRetinaSupport: true

    - name: Printer
      url: //stamen-tiles-{s}.a.ssl.fastly.net/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Printer</a>'

    - name: Openstreetmap
      url: //{s}.tile.osm.org/{z}/{x}/{y}.png
      attribution: 'Map data &copy; <a href="https://openstreetmap.org">OpenStreetMap</a> contributors'
      maxZoom: 16

  overlays:
    - type: stops
      name: stops
      visible: true
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconColor: "#fff"
      minZoom: 15
      parentStations: true
      minZoomStation: 17

    - type: bike-rental
      name: bikesharing
      modes:
        - BICYCLE_RENT
      companies:
        - BZ
        - ME
        - PAPIN
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#ead896"
      iconColor: "#5d5d5d"

    - type: car-rental
      name: carsharing
      modes:
        - CAR_RENT
      companies:
        - SUEDTIROL
      api: ${CARSHARING_BASEURL}/carsharing/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#d9bd48"
      iconColor: "#5d5d5d"
      filters:
        company:
          enabled: true
          label: carsharing_company
          values:
            - value: Car Sharing Südtirol Alto Adige
              enabled: true
            - value: Car Sharing Trentino
              enabled: true
            # - value: undefined
            #   enabled: true
        # bookahead:
        #   enabled: true
        #   label: carsharing_bookahead
        #   values:
        #     - value: 'yes'
        #       enabled: true
        #     - value: 'no'
        #       enabled: true

    - type: charger
      name: charger
      api: ${CHARGER_BASEURL}/charger/stations.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#FAA61F"
      iconColor: "#5d5d5d"
      filters:
        provider:
          enabled: true
          label: charger_provider
          values:
            - value: DriWe
              enabled: true
            - value: H2 Center
              enabled: true
            - value: Neogy
              enabled: true
            - value: Route220
              enabled: true
            # - value: AER
            #   enabled: true
            - value: Alperia Smart Mobility
              enabled: true
            # - value: AP_GEN
            #   enabled: true
            # - value: ASD
            #   enabled: true
            # - value: ASM
            #   enabled: true
            # - value: EDY
            #   enabled: true
            # - value: NHP
            #   enabled: true
        accessType:
          enabled: true
          label: charger_accesstype
          values:
            - value: PUBLIC
              enabled: true
            - value: PRIVATE
              enabled: true
            - value: PRIVATE_WITHPUBLICACCESS
              enabled: true
            # - value: undefined
            #   enabled: true
        plugsTypes:
          enabled: true
          label: charger_plugstypes
          values:
            - value: 700 bar small vehicles
              enabled: true
            - value: IEC 62196-2 type 2 outlets (all amperage and phase)
              enabled: true
            - value: Type2Mennekes
              enabled: true
            - value: CHAdeMO
              enabled: true
            - value: CCS
              enabled: true
            - value: Schuko
              enabled: true
            - value: OTHER
              enabled: true
            # - value: UNKNOWN
            #   enabled: true
        # reservable:
        #   enabled: true
        #   label: charger_reservable
        #   values:
        #     - value: 'yes'
        #       enabled: true
        #     - value: 'no'
        #       enabled: true
            # - value: undefined
            #   enabled: true
            # - value: 'null'
            #   enabled: true


    - type: parking
      name: parking
      #visible: true
      #TODO enable clustering by config -> cluster: true
      #api: ${PARKING_BASEURL}/parking/stations.json
      api: ${PARKING_BASEURL}/parking/all.json
      iconWidth: 42
      iconHeight: 50
      iconMarkerColor: "#b0d1ef"
      iconColor: "#5d5d5d"

    - type: drt
      name: ondemand
      api: ${DRT_BASEURL}/drt/all.json
      pollingInterval: 5000
      iconWidth: 15
      iconHeight: 15
      iconMarkerColor: "#095980"
      iconVehicleColor: "#095980"
      iconColor: "#fff"
      areas:
        1:
          name: 'Area Esterna'
          color: 'red'
        2:
          name: 'Area Principale'
          color: 'green'
        3:
          name: 'Area Esterna'
          color: 'red'

    # - type: parking-sensors
    #   name: parking-sensors
    #   api: ${PARKING_BASEURL}/parking/sensors.json
    #   iconWidth: 42
    #   iconHeight: 50
    #   iconMarkerColor: "#b0d1ef"
    #   iconColor: "#5d5d5d"
    # real-time vehicles config
    # - type: vehicles
    #   name: Real-Time Buses and Trains
    #   api: https://otp.openmove.com/gtfs/rt/vehicles
    #   #pauseAnimationOnZoom: false # note: when true, MOD+vehicles has issues with multiple (additive) ws calls
    #   refresh: 5
    #   default: 'all'
    #
    # - type: micromobility-rental
    #   name: Bird E-scooter Locations
    #   modes:
    #     - MICROMOBILITY_RENT
    #   companies:
    #     - BIRD
    #   mapSymbols:
    #     - maxZoom: 12
    #       minZoom: 0
    #       type: circle
    #       pixels: 3
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 15
    #       minZoom: 13
    #       type: circle
    #       pixels: 5
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 20
    #       minZoom: 16
    #       fillColor: "#656565"
    #       type: marker
    #
    #
    #
    # - type: micromobility-rental
    #   name: Lime E-scooter Locations
    #   modes:
    #     - MICROMOBILITY_RENT
    #   companies:
    #     - LIME
    #   mapSymbols:
    #     - maxZoom: 12
    #       minZoom: 0
    #       type: circle
    #       pixels: 3
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 15
    #       minZoom: 13
    #       type: circle
    #       pixels: 5
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 20
    #       minZoom: 16
    #       fillColor: "#656565"
    #       type: marker
    #
    # - type: micromobility-rental
    #   name: Razor E-scooter Locations
    #   modes:
    #     - MICROMOBILITY_RENT
    #   companies:
    #     - RAZOR
    #   mapSymbols:
    #     - maxZoom: 12
    #       minZoom: 0
    #       type: circle
    #       pixels: 3
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 15
    #       minZoom: 13
    #       type: circle
    #       pixels: 5
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 20
    #       minZoom: 16
    #       fillColor: "#656565"
    #       type: marker
    #
    #
    # - type: micromobility-rental
    #   name: Spin E-scooter Locations
    #   modes:
    #     - MICROMOBILITY_RENT
    #   companies:
    #     - SPIN
    #   mapSymbols:
    #     - maxZoom: 12
    #       minZoom: 0
    #       type: circle
    #       pixels: 3
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 15
    #       minZoom: 13
    #       type: circle
    #       pixels: 5
    #       fillColor: "#656565"
    #       strokeColor: "#CCCCCC"
    #     - maxZoom: 20
    #       minZoom: 16
    #       fillColor: "#656565"
    #       type: marker
    #
    # - type: park-and-ride
    #   name: Aree Park & Ride
    #   maxTransitDistance: 1000
    #   modes:
    #     - CAR_PARK

# Mode selector configuration
modes:
  transitModes:
    - mode: BUS
      label: bus
    - mode: RAIL
      label: train
    - mode: GONDOLA
      label: funicular
    # - mode: TRAM
    #   label: MAX & Streetcar
    #   showWheelchairSetting: true

  #old conf accessModes:
  #   - mode: BICYCLE_RIDE
  #     label: bike_ride
  #   - mode: BICYCLE_RENT
  #     label: bikesharing_ride
  #   #  company: Bikesharing
  #   # - mode: MICROMOBILITY_RENT
  #   #   label: Transit + E-scooter
  #   - mode: CAR_PARK
  #     label: park_ride
  #   - mode: CAR_RENT
  #     label: carsharing_ride
  #     company: CAR2GO
  #   #   showWheelchairSetting: false
  #   - mode: MICROMOBILITY_RENT
  #     label: micromobility_ride
  accessModes:
    - mode: BICYCLE
      label: bike_ride
    - mode: BICYCLE_RENT
      label: bikesharing_ride
    - mode: CAR_PARK
      label: park_ride
    - mode: CAR_RENT
      label: carsharing_ride
    - mode: MICROMOBILITY
      label: micromobility_ride
    # - mode: MICROMOBILITY_RENT
    #   label: Transit + E-scooter

  # which exclusive modes to show. This involves using a single mode and no
  # transit for the duration of the trip. Further configurations of
  # `bicycleModes`, `micromobilityModes` and/or `carModes` are needed as
  # desired, but no extra configuration is needed for a WALK exclusive mode.
  exclusiveModes:
    - WALK
    - BICYCLE
    - MICROMOBILITY

  bicycleModes:
    - mode: BICYCLE
      label: my_bike
      iconWidth: 18
    - mode: BICYCLE_RENT
      label: bikesharing
      iconWidth: 36

# A list of private transportation operators. These are either companies that
# provide rental vehicles or transportation network companies. Companies that
# have multiple modes of transport should have all modes listed as a string with
# commas. For example: BICYCLE_RENT,MICROMOBILITY_RENT.
companies:
    - id: BZ
      label: Bikesharing BZ
      modes: BICYCLE_RENT

    - id: ME
      label: Bikesharing Meran
      modes: BICYCLE_RENT

    - id: PAPIN
      label: Bike Rental Papin
      modes: BICYCLE_RENT

    - id: CAR2GO
      label: CarSharing
      modes: CAR_RENT

#   - id: BIRD
#     label: Bird
#     modes: MICROMOBILITY_RENT
#   - id: LIME
#     label: Lime
#     modes: MICROMOBILITY_RENT
#   - id: RAZOR
#     label: Razor
#     modes: MICROMOBILITY_RENT
#   - id: SPIN
#     label: Spin
#     modes: MICROMOBILITY_RENT


            #TEST
            #
errorMessages:
  - id: 404
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.
  - id: 405
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.
  - id: 480
    msg: Nessun percorso trovato. Prova a modificare le impostazioni del tuo viaggio.

dateTime:
  timeFormat: HH:mm
  dateFormat: DD/MM/YYYY
  longDateFormat: D MMMM YYYY
