version: '3'

networks:
  default:
    driver: bridge

services:

  journey:
    container_name: openmove-otp-journey
    ports: ["8070:80"]
    #restart: "always"
    image: openmove_otp_journey:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        OTP_RR_BRANCH: mentor-meran
        OTP_UI_BRANCH: master
        API_HOST: http://otp
        API_PATH: /otp/routers/openmove
        API_PORT: 8080

  otp:
    container_name: openmove-otp
    ports: ["8080:8080"]
    #restart: "always"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=2G
      - BUILD_GRAPH=False
    volumes:
      - /opt/odh-mentor-otp/:/data/

  build:
    container_name: openmove-build
    ports: ["8090:8080"]
    restart: "no"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=8G
      - BUILD_GRAPH=True
      - DOWNLOAD_DATA=True
      - BACKUP_GRAPH=True
      - GTFS_FILE=200804_ExportGTFS.zip
    volumes:
      - /opt/odh-mentor-otp/:/data/
      #- ./docker-entrypoint.sh:/docker-entrypoint.sh
      #uncomment to test script
