#
# Require a .env file contains all environment vars
# look contents of file _dot.env.example
#
version: '3'

networks:
  default:
    driver: bridge

services:

  journey:
    container_name: openmove-journey
    ports:
      - "8081:80"
    image: openmove_journey:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        API_HOST: $API_HOST
        API_PATH: $API_PATH
        API_PORT: $API_PORT
        CARSHARING_BASEURL: $CARSHARING_BASEURL
        CHARGER_BASEURL: $CHARGER_BASEURL
        DRT_BASEURL: $DRT_BASEURL
        GEOCODER_BASEURL: $GEOCODER_BASEURL
        PARKING_BASEURL: $PARKING_BASEURL
        TRAFFIC_BASEURL: $TRAFFIC_BASEURL
        ## debug of remote instance
        #API_HOST: https://otp.opendatahub.testingmachine.eu
        #API_PORT: 443
        #API_PATH: /otp/routers/openmove
        #GEOCODER_BASEURL: https://geocoder.otp.opendatahub.testingmachine.eu/v1
        #PARKING_BASEURL: https://parking.otp.opendatahub.testingmachine.eu
        #DRT_BASEURL:  https://drt.otp.opendatahub.testingmachine.eu
        #CHARGER_BASEURL: https://charger.otp.opendatahub.testingmachine.eu
        #CARSHARING_BASEURL: https://carsharing.otp.opendatahub.testingmachine.eu
        #TRAFFIC_BASEURL: https://traffic.otp.opendatahub.testingmachine.eu
        ##
        #GOOGLE_ANALYTICS_ID: $GOOGLE_ANALYTICS_ID
    # depends_on:
    #  - geocoder
    #  - otp
    #  - parking
    #  - charger
    #  - carsharing
    #  - traffic
    #  - drt

  carsharing:
    container_name: openmove-carsharing
    ports:
      - "8091:8091"
    image: openmove_carsharing:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/carsharing/Dockerfile

  charger:
    container_name: openmove-charger
    ports:
      - "8093:8093"
    image: openmove_charger:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/charger/Dockerfile

  drt:
      container_name: openmove-drt
      ports:
        - "8095:8095"
      image: openmove_drt:latest
      build:
        context: ./
        dockerfile: infrastructure/docker/drt/Dockerfile
  gbfs:
      container_name: openmove-gbfs
      ports:
        - "8089:8089"
      image: openmove_gbfs:latest
      build:
        context: ./
        dockerfile: infrastructure/docker/gbfs/Dockerfile

  geocoder:
    container_name: openmove-geocoder
    ports:
      - "8088:8088"
    image: openmove_geocoder:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/geocoder/Dockerfile
    #TODO ONLY FOR DEBUG
    #volumes:
    #  - ./config.yml:/home/config.yml
    #  - ./index.js:/home/index.js
    environment:
      API_HOST: otp
      API_PATH: /otp/routers/openmove
      API_PORT: 8080
      HERE_APPID: ''
      HERE_APPCODE: ''
      HERE_APIKEY: ''

  parking:
    container_name: openmove-parking
    ports:
      - "8092:8092"
    image: openmove_parking:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/parking/Dockerfile

  traffic:
    container_name: openmove-traffic
    ports:
      - "8094:8094"
    image: openmove_traffic:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/traffic/Dockerfile

  otp:
    container_name: openmove-otp
    ports:
      - "8080:8080"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=4G
      - BUILD_GRAPH=False
      - OTP_OFFICIAL=False
      - GTFS_FILE=latestGTFS.zip
      - GTFS_URL=ftp://ftp.sta.bz.it/gtfs/google_transit_shp.zip
      - GTFS_URL_UPDATETIME=0 * * * *
      - GTFS_URL_UPDATEHOOK=''
    volumes:
      - /opt/odh-mentor-otp/:/data/
    depends_on:
      #TODO - drt
      - gbfs
      - parking
      - charger
      - carsharing

  build:
    container_name: openmove-build
    ports:
      - "8090:8080"
    restart: "no"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=10G
      - BUILD_GRAPH=True
      - OTP_OFFICIAL=False
      - DOWNLOAD_DATA=False
      - BACKUP_GRAPH=False
      - GTFS_FILE=latestGTFS.zip
      - UPDATERS=True
      - GBFS_HOST=http://gbfs:8089
      - GBFS_VERSION=1
      #- GBFS_VERSION=2.1
      - GTFS_RT_URL=https://efa.sta.bz.it/gtfs-r/
      - GTFS_FEED_ID=1
      - CARSHARING_HOST=http://carsharing:8091
      - PARKING_HOST=http://parking:8092
    volumes:
      - /opt/odh-mentor-otp/:/data/
      #- infrastructure/docker/docker-entrypoint.sh:/docker-entrypoint.sh
      #uncomment to test script    
