version: '3'

networks:
  default:
    driver: bridge

services:

  journey:
    container_name: openmove-otp-journey
    ports: ["80:80"]
    image: openmove_otp_journey:test-geocoder
    build:
      context: ./
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        API_HOST: http://localhost
        API_PATH: /otp/routers/openmove
        API_PORT: 8080
        GEOCODER_BASEURL: http://localhost:8088/v1
    depends_on:
      - geocoder
      - otp

  geocoder:
    container_name: openmove-geocoder
    ports: ["8088:8088"]
    image: openmove_geocoder:latest
    build:
      context: ./geocoder/
      dockerfile: ./Dockerfile

  gbfs:
    container_name: openmove-gbfs
    ports: ["8089:8089"]
    image: openmove_gbfs:latest
    build:
      context: ./gbfs/
      dockerfile: ./Dockerfile

  otp:
    container_name: openmove-otp
    ports: ["8080:8080"]
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=4G
      - BUILD_GRAPH=False
    volumes:
      - /opt/odh-mentor-otp/:/data/
    depends_on:
      - gbfs

  build:
    container_name: openmove-build
    ports: ["8090:8080"]
    restart: "no"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=10G
      - BUILD_GRAPH=True
      - DOWNLOAD_DATA=True
      - BACKUP_GRAPH=False
      - GTFS_FILE=200804_ExportGTFS.zip
      - UPDATERS=True
      - GBFS_HOST=http://gbfs
      - GBFS_PORT=8089
    volumes:
      - /opt/odh-mentor-otp/:/data/
      #- infrastructure/docker/docker-entrypoint.sh:/docker-entrypoint.sh
      #uncomment to test script
    restart: "no"
