version: '3'

networks:
  default:
    driver: bridge

services:

  journey:
    container_name: openmove-journey
    ports: ["80:80"]
    image: openmove_journey:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        API_HOST: http://localhost
        API_PATH: /otp/routers/openmove
        API_PORT: 8080
        GEOCODER_BASEURL: http://localhost:8088/v1
    depends_on:
      - geocoder
      - otp

  geocoder:
    container_name: openmove-geocoder
    ports: ["8088:8088"]
    image: openmove_geocoder:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/geocoder/Dockerfile
    #TODO ONLY FOR DEBUG
    #volumes:
    #  - ./config.yml:/home/config.yml
    #  - ./index.js:/home/index.js
    # environment:
    #   API_HOST: otp
    #   API_PATH: /otp/routers/openmove
    #   API_PORT: 8080

  gbfs:
    container_name: openmove-gbfs
    ports: ["8089:8089"]
    image: openmove_gbfs:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/gbfs/Dockerfile

  otp:
    container_name: openmove-otp
    ports: ["8080:8080"]
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=4G
      - BUILD_GRAPH=False
      - OFFICIAL=False
    volumes:
      - /opt/odh-mentor-otp/:/data/
    depends_on:
      - gbfs

  build:
    container_name: openmove-build
    ports: ["8090:8080"]
    restart: "no"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/otp/Dockerfile
    environment:
      - JAVA_MX=10G
      - BUILD_GRAPH=True
      - OFFICIAL=False
      - DOWNLOAD_DATA=False
      - BACKUP_GRAPH=False
      - GTFS_FILE=urbano_tt.zip
      - UPDATERS=True
      - GBFS_HOST=http://gbfs
      - GBFS_PORT=8089
      - GBFS_VERSION=1
      - GTFS_RT_URL=https://efa.sta.bz.it/gtfs-r/
      - GTFS_FEED_ID=1
      #- GBFS_VERSION=2.1
    volumes:
      - /opt/odh-mentor-otp/:/data/
      #- infrastructure/docker/docker-entrypoint.sh:/docker-entrypoint.sh
      #uncomment to test script
    restart: "no"
