version: '3'

networks:
  default:
    driver: bridge

services:

  otp-app:
    container_name: openmove-otp-app
    ports: ["8070:80"]
    #restart: "always"
    image: openmove_otp_app:latest
    build:
      context: ./otp-app/
      dockerfile: ./Dockerfile
      args:
        API_HOST: http://localhost
        API_PATH: /otp/routers/openmove
        API_PORT: 8080
  gbfs:
    container_name: openmove-gbfs
    ports: ["8089:8089"]
    #restart: "always"
    image: openmove_gbfs:latest
    build:
      context: ./gbfs/
      dockerfile: ./Dockerfile

  otp:
    container_name: openmove-otp
    ports: ["8080:8080"]
    #restart: "always"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/Dockerfile
      args:
        OTP_VERSION: 1.4.0
    environment:
      - JAVA_MX=4G
      - BUILD_GRAPH=False
    volumes:
      - ./data/:/data/

  build:
    container_name: openmove-build
    ports: ["8090:8080"]
    restart: "no"
    image: openmove_otp:latest
    build:
      context: ./
      dockerfile: infrastructure/docker/Dockerfile
    environment:
      - JAVA_MX=8G
      - BUILD_GRAPH=True
      - DOWNLOAD_DATA=False
      - BACKUP_GRAPH=False
      - GTFS_FILE=200804_ExportGTFS.zip
      - UPDATERS=False
      - GBFS_HOST=http://gbfs
      - GBFS_PORT=8089
    volumes:
      - ./data/:/data/
      #- ./docker-entrypoint.sh:/docker-entrypoint.sh
      #uncomment to test script
