server:
  port: 8093
  polling_interval: 10

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #headers:
    # User-Agent: OpenMove-Charger-Client
  stations:
    path: /v2/flat%2Cnode/ChargerStation/*/latest?distinct=true&limit=-1
  sensors:
    path: /v2/flat%2Cnode/ParkingSensor/*/latest?distinct=true&limit=-1
