environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8093
dev:
  listen_port: 9093
  polling_interval: 2

polling_interval: 120

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    method: GET
    port: 443
    #path: /v2
    headers:
      User-Agent: OpenMove-Api-Client

  stations:
    path: /v2/flat%2Cnode/EChargingStation/*/latest?distinct=true&limit=-1&where=scoordinate.bbc.(10,46,12.8,47.2)
  plugs:
    path: /v2/flat%2Cnode/EChargingPlug/*/latest?distinct=true&limit=-1&where=scoordinate.bbc.(10,46,12.8,47.2)
