version: '3'

networks:
  default:
    driver: bridge

services:

  otp-app:
    container_name: openmove-otp-app
    ports: ["8070:80"]
    #restart: "always"
    image: openmove_otp_app:latest
    build:
      context: ./otp-app/
      dockerfile: ./Dockerfile
      args:
        OTP_RR_BRANCH: mentor-meran
        OTP_UI_BRANCH: master
