environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8091
dev:
  listen_port: 9091
  polling_interval: 2

polling_interval: 120

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    method: GET
    port: 443
    #path: /v2
    headers:
      User-Agent: OpenMove-Api-Client

  stations:
    path: /v2/flat%2Cnode/CarsharingStation?distinct=true&limit=500
  cars:
    path: /v2/flat%2Cnode/CarsharingCar?distinct=true&limit=500

uri:
    meran:
      web: https://www.comune.merano.bz.it
    bozen:
      web: https://bolzano.ecospazio.it

test_env: ${ENV_VAR_TEST}