server:
  port: 8091
  polling_interval: 10

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #headers:
    # User-Agent: OpenMove-Parking-Client
  stations:
    path: /v2/flat%2Cnode/CarsharingStation?distinct=true
  cars:
    path: /v2/flat%2Cnode/CarsharingCar?distinct=true
