server:
  port: 8089
  polling_interval: 10

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #path: /v2
    #headers:
    # User-Agent: OpenMove-Bikesharing-Client
    #example of custom host and port for specific endpoint
    #hostname: ${STATIONS_HOST}
    #port: ${STATIONS_PORT}

  stations:
    path: /v2/flat%2Cnode/BikesharingStation?distinct=true

  bays:
    path: /v2/flat%2Cnode/Bicyclestationbay?distinct=true

  bikes:
    path: /v2/flat%2Cnode/Bicycle?distinct=true&limit=500

uri:
    meran:
        android: https://play.google.com/store/apps/details?id=de.moqo.work&hl=en_US"
        ios: https://apps.apple.com/de/app/moqo/id1385011262
        web: https://www.comune.merano.bz.it/it/Bikesharing
    bozen:
        web: https://bolzano.ecospazio.it/
