environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8088
dev:
  listen_port: 9088
  min_text_length: 1

#TODO cache_ttl: 0
default_lang: 'en'
min_text_length: 3

endpoints:
  default:
    #priority: 1
    #TODO parameter by sorted results
    #size: 10 result size for each endpoints
    hostname: tourism.opendatahub.bz.it
    port: 443
    #hostname: localhost
    #port: 9090
    size: 5
    #method: 'GET'
    headers:
      User-Agent: OpenMove-Api-Client
      Referer: https://journey.opendatahub.bz.it
    layer: venue

  here:
    appId: ${HERE_APPID}
    appCode: ${HERE_APPCODE}
    apiKey: ${HERE_APIKEY}
    size: 5
    layer: address
    boundary:
      rect:
        minLon: 10.470121
        maxLon: 12.255011
        minLat: 46.188280
        maxLat: 47.088780
    #Suedtirol 10.470121,46.188280,12.255011,47.088780

  opentripplanner:
    #TODO priority: 100
    hostname: ${API_HOST}
    #hostname: localhost
    # docs  http://dev.opentripplanner.org/apidoc/1.4.0/resource_GeocoderResource.html
    path: /otp/routers/default/geocode?query={{text}}
    #TODO use env var API_PATH
    port: ${API_PORT}
    #size: 10
    layer: stops

  accommodations:
    #TODO priority: 50
    path: /v1/Accommodation?searchfilter={{text}}&pagesize={{size}}&language={{lang}}&poitype=447&active=true&fields=Id,AccoDetail.{{lang}}.Name,Latitude,Longitude
    #size: 10
    layer: venue
    #in pelias venue is a POIs

  ODHActivityPoi:
    path: /v1/ODHActivityPoi/?searchfilter={{text}}&pagesize={{size}}&language={{lang}}&poitype=447&active=true&fields=Id,Detail.{{lang}}.Title,GpsInfo
    #size: 10
    layer: venue
