server:
  port: 8088
  #TODO cache_ttl: 0
  default_lang: 'en'
  mintextlength: 3

endpoints:
  default:
    #priority: 1
    #TODO parameter by sorted results
    #size: 10 result size for each endpoints
    hostname: tourism.opendatahub.bz.it
    port: 443
    size: 5
    #method: 'GET'
    #headers:
    # User-Agent: OpenMove-Geocoder-Client
    layer: venue

  here:
    #hostname: api.here.com
    #path: /6.2/geocode.json
    ##provided by npm heremap
    appId: ${HERE_APPID}
    appCode: ${HERE_APPCODE}
    #apiKey: ${HERE_APIKEY}
    size: 5
    layer: address
    #define pelias layer in responses
    bbox:
      latM: 46.749271
      lngm: 10.991821
      latm: 46.431232
      lngM: 11.475220
      #suedtirol bbox 

  opentripplanner:
    #TODO priority: 100
    hostname: ${API_HOST}
    #hostname: localhost
    # docs  http://dev.opentripplanner.org/apidoc/1.4.0/resource_GeocoderResource.html
    path: /otp/routers/default/geocode?query={{text}}
    #TODO use env var API_PATH
    port: ${API_PORT}
    size: 5
    layer: stops

  accommodations:
    #TODO priority: 50
    path: /api/Accommodation?searchfilter={{text}}&pagesize={{size}}&language={{lang}}&poitype=447&active=true&fields=Id,AccoDetail.{{lang}}.Name,Latitude,Longitude
    size: 5
    layer: venue
    #in pelias venue is a POIs

  ODHActivityPoi:
    path: /api/ODHActivityPoi/?searchfilter={{text}}&pagesize={{size}}&language={{lang}}&poitype=447&active=true&fields=Id,Detail.{{lang}}.Title,GpsInfo
    size: 5
    layer: venue
