# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8095
dev:
  listen_port: 9095

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it

  vehicles:
    path: /v2/flat,node/ON_DEMAND_VEHICLE/*/latest
  stops:
    path: /v2/flat,node/ON_DEMAND_STOP
  trips:
    path: /v2/flat,node/ON_DEMAND_ITINERARY/*/latest

gtfsflex_filename: 'gtfs-flex-%T.zip'
# %T is Unix Epoch

#TODO use in csv.js
# gtfs_flex_agency:
#   id: DRT
#   name: Call Bus
#   url: https://www.sasabz.it/callbus
#   timezone: Europe/Rome
#   lang: it
#   phone: "+390471706633"
