environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8096
dev:
  listen_port: 9096
#   polling_interval: 3

polling_interval: 120
#seconds

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    headers:
      Authorization: 'bearer ${TOKEN}'

  # stations:
  #   path: /v2/flat%2Cnode/ParkingStation/free/latest?distinct=true&limit=-1&where=mperiod.eq.300
  stations:
    #path: /v2/flat%2Cnode/VMS/*?distinct=true&select=*&where=&limit=-1
    path: /v2/flat%2Cnode/VMS/*/latest?distinct=true&select=tmeasurements,scoordinate,smetadata,scode,sname,mvalue,sorigin&where=sactive.eq.true,and(sorigin.eq.A22)&limit=1000
    #for A22 add: ,and(sorigin.eq.A22)
  station:
    path: "/v2/tree/VMS/*?where=scode.eq.<%=scode%>&select=*"
    #path: /v2/tree/VMS/*?where=scode.eq.%22A22:100:1%22
    #use always `tree` for one instance

##bbox a22
#&where=scoordinate.bbc.(10,46,12.8,47.2)
#codes:
#https://github.com/noi-techpark/bdp-commons/blob/main/data-collectors/vms-a22/src/main/resources/it/bz/noi/a22/vms/streetcodes.csv

#https://drive.google.com/file/d/1Tfa-bOm-skr_Rml4rGUuuOZuCV4bYutF/view
pmv_types:
  1: TIPO A
  2: LAVAGNE
  3: TIPO I
  4: TIPO D
  5: CARRELLI MOBILI
  7: TIPO B
  8: VIABILITA ORDINARIA
  9: TIPO E
  10: SMALL
  11: MONTI E
  14: TIPO G
  15: TIPO L
  16: VERBAINFO
  19: PARCHEGGI

directions_types:
  1: Sud
  2: Nord
  3: Entrambe
  4: ''
  #4 (o altro valore numerico) = Non definito

