environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8096
dev:
  listen_port: 9096
  polling_interval: 2

polling_interval: 120

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #path: /v2
    headers:
      User-Agent: OpenMove-Api-Client

  # stations:
  #   path: /v2/flat%2Cnode/ParkingStation/free/latest?distinct=true&limit=-1&where=mperiod.eq.300
  stations:
    path: /v2/flat/VMS/?distinct=true&select=*&where=&limit=-1
    #path: /v2/*/VMS/*?where=scode.eq.%22A22:100:1%22
  station:
    path: "/v2/tree/VMS/*?where=scode.eq."
    #TODO use template


#codes:
#https://github.com/noi-techpark/bdp-commons/blob/main/data-collectors/vms-a22/src/main/resources/it/bz/noi/a22/vms/streetcodes.csv