environments:
  default: prod
  #default environment if NODE_ENV is not defined

prod:
  listen_port: 8096
dev:
  listen_port: 9096
#   polling_interval: 3

polling_interval: 120
#seconds

noauth: false

endpoints:
  default:
    hostname: mobility.api.opendatahub.bz.it
    port: 443
    #path: /v2
    headers:
      User-Agent: OpenMove-Api-Client
      Authorization: 'bearer ${TOKEN}'

  # stations:
  #   path: /v2/flat%2Cnode/ParkingStation/free/latest?distinct=true&limit=-1&where=mperiod.eq.300
  stations:
    #path: /v2/flat%2Cnode/VMS/*?distinct=true&select=*&where=&limit=-1
    path: /v2/flat,node/VMS/*/latest?select=tmeasurements,scoordinate,smetadata,scode,sname,mvalue,sorigin&where=sactive.eq.true,and(sorigin.eq.A22)&limit=200
    #for A22 add: ,and(sorigin.eq.A22)
  station:
    path: "/v2/tree/VMS/*?where=scode.eq.<%=scode%>&select=*"
    #path: /v2/tree/VMS/*?where=scode.eq.%22A22:100:1%22
    #use always `tree` for one instance

##bbox a22
#&where=scoordinate.bbc.(10,46,12.8,47.2)
#codes:
#https://github.com/noi-techpark/bdp-commons/blob/main/data-collectors/vms-a22/src/main/resources/it/bz/noi/a22/vms/streetcodes.csv