version: "3.4"

services:
  app:
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      JAVA_MX: ${JAVA_MX}
      BUILD_GRAPH: ${BUILD_GRAPH}
      DOWNLOAD_DATA: ${DOWNLOAD_DATA}
      BACKUP_GRAPH: ${BACKUP_GRAPH}
    volumes:
      - /opt/odh-mentor-otp/:/data/
    ports:
      - ${SERVER_PORT}:8080
