version: "3.4"

services:
  journey:
    image: ${DOCKER_IMAGE_JOURNEY}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      OTP_RR_BRANCH: ${OTP_RR_BRANCH}
      OTP_UI_BRANCH: ${OTP_UI_BRANCH}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_PATH: ${API_PATH}
    ports:
      - ${SERVER_PORT_JOURNEY}:80

  otp:
    image: ${DOCKER_IMAGE_OTP}:${DOCKER_TAG}
    restart: unless-stopped
    environment:
      JAVA_MX: ${JAVA_MX}
      BUILD_GRAPH: ${BUILD_GRAPH}
      DOWNLOAD_DATA: ${DOWNLOAD_DATA}
      BACKUP_GRAPH: ${BACKUP_GRAPH}
      GBFS_HOST: ${GBFS_HOST}
      GBFS_VERSION: ${GBFS_VERSION}
      CARSHARING_HOST: ${CARSHARING_HOST}
      PARKING_HOST: ${PARKING_HOST}
      CHARGER_HOST: ${CHARGER_HOST}      
      UPDATERS: "True"
      OFFICIAL: ${OFFICIAL}
    volumes:
      - /opt/odh-mentor-otp/:/data/
    ports:
      - ${SERVER_PORT_OTP}:8080

  gbfs:
    image: ${DOCKER_IMAGE_GBFS}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
     - ${DOCKER_GBFS_PORT}:8089

  geocoder:
    image: ${DOCKER_IMAGE_GEOCODER}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_GEOCODER_PORT}:8088
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      API_PATH: ${API_PATH}
  carsharing:
    image: ${DOCKER_IMAGE_CARSHARING}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_CARSHARING_PORT}:8091
  parking:
    image: ${DOCKER_IMAGE_PARKING}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_PARKING_PORT}:8092
