version: "3.4"

services:
  journey:
    image: ${DOCKER_IMAGE_JOURNEY}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SERVER_PORT_JOURNEY}:80

  otp-react-redux:
    image: ${DOCKER_IMAGE_OTP_REACT_REDUX}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${SERVER_PORT_OTP_REACT_REDUX}:80

  otp:
    image: ${DOCKER_IMAGE_OTP}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${SERVER_PORT_OTP}:8080
  
  gbfs:
    image: ${DOCKER_IMAGE_GBFS}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
     - ${DOCKER_GBFS_PORT}:8089

  geocoder:
    image: ${DOCKER_IMAGE_GEOCODER}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_GEOCODER_PORT}:8088
    env_file:
      - .env
  carsharing:
    image: ${DOCKER_IMAGE_CARSHARING}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_CARSHARING_PORT}:8091
  parking:
    image: ${DOCKER_IMAGE_PARKING}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_PARKING_PORT}:8092
  drt:
    image: ${DOCKER_IMAGE_DRT}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_DRT_PORT}:8095
  charger:
    image: ${DOCKER_IMAGE_ECHARGING}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_ECHARGING_PORT}:8093
  traffic:
    image: ${DOCKER_IMAGE_TRAFFIC}:${DOCKER_TAG}
    restart: unless-stopped
    ports:
      - ${DOCKER_TRAFFIC_PORT}:8094
  amarillo:
    image: ${DOCKER_IMAGE_AMARILLO}:${DOCKER_TAG}
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${DOCKER_AMARILLO_PORT}:80
    volumes:
      - /opt/odh-mentor-otp/amarillo/:/app/data/
