version: "3.4"

services:
  journey:
    image: ${DOCKER_IMAGE_JOURNEY}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/journey/Dockerfile
      args:
        - API_HOST: ${API_HOST}
        - API_PORT: ${API_PORT}
        - API_PATH: ${API_PATH}

  otp:
    image: ${DOCKER_IMAGE_OTP}:${DOCKER_TAG}
    build:
      context: ../
      dockerfile: infrastructure/docker/otp/Dockerfile
