version: "3.4"

services:
  otp:
    image: ${DOCKER_IMAGE_OTP}:${DOCKER_TAG}
    restart: "no"
    environment:
      JAVA_MX: ${JAVA_MX}
      BUILD_GRAPH: ${BUILD_GRAPH}
      DOWNLOAD_DATA: ${DOWNLOAD_DATA}
      BACKUP_GRAPH: ${BACKUP_GRAPH}
      GTFS_FILE: ${GTFS_FILE}
      GBFS_HOST: ${GBFS_HOST}
      GBFS_PORT: ${GBFS_PORT}
      GBFS_VERSION: ${GBFS_VERSION}
      UPDATERS: ${UPDATERS}
      GEOCODER_BASEURL: ${GEOCODER_BASEURL}
      GTFS_RT_URL: ${GTFS_RT_URL}
      GTFS_FEED_ID: ${GTFS_FEED_ID}
      OFFICIAL: ${OFFICIAL}
    volumes:
      - /opt/odh-mentor-otp/:/data/
